Dev om
ombothe08/PathGenerationOfCleaningBot pull request #1
Opened 2024-05-07 10:52 UTC by ombothe08

Updated the srs, added the readme.md file

2024-05-08 06:31 UTC, vinayaksutar requested changes
I don't see the finish sketch button, as per yesterday's discussion. If you have any other workflow in mind please let me know.

2024-05-08 09:19 UTC, ombothe08 commented
I have updated the UI added the finish sketch button please have a look.

2024-05-08 10:42 UTC, vinayaksutar commented
re-request review so that I can approve it

2024-05-09 09:23 UTC, vinayaksutar approved these changes

2024-05-10 06:08 UTC, merged